# .circleci/config.yml
version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: sudo apt install -y gcc g++ cmake valgrind
      - run: mkdir build && mkdir artifacts
      - run: pwd
      - run: ls
      - run: cd build && cmake ..
      - run: cmake --build build -j6
      - run: cmake --install build --prefix artifacts

workflows:
  build:
    jobs:
      - build-medium