# .circleci/config.yml
version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: sudo apt install zip gcc g++ cmake # valgrind
      - run:
          name: Environment info
          command: |
            pwd
            uname -a
            lscpu
            cat /proc/cpuinfo
            ls
      - run: 
          name: Build and install
          command: |
            mkdir build && mkdir artifacts
            cd build
            cmake ..
            cmake --build . -j6
            cmake --install . --prefix ../artifacts
            cd ..
            zip artifacts artifacts

      - store_artifacts: 
          path: artifacts.zip
          destination: artifacts

workflows:
  build:
    jobs:
      - build-medium